services:
  - type: web
    name: tutormaven-api
    env: node
    rootDir: api
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tutormaven-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: tutormaven-redis
          property: connectionString

databases:
  - name: tutormaven-postgres
    plan: free

redis:
  - name: tutormaven-redis
    plan: free

